vich_uploader:
    db_driver: orm

    mappings:
        infos:
            uri_prefix: /images/infos
            upload_destination: '%kernel.project_dir%/public/images/infos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
